<template>
  <footer class="transparency-footer">
    <p class="transparency-text">
      This letter is generated by AI, not written by a human.
      <NuxtLink to="/about" class="transparency-link">Learn more</NuxtLink>
    </p>
  </footer>
</template>

<script setup lang="ts">
// No props needed
</script>

<style scoped>
.transparency-footer {
  @apply w-full;
  @apply mt-12 mb-8;
  @apply text-center;
}

.transparency-text {
  @apply text-sm;
  @apply text-gray-500;
}

.transparency-link {
  @apply underline;
  @apply text-gray-600;
  @apply hover:text-gray-800;
  @apply transition-colors;
}
</style>

