# MVP Scope Refinement Workflow
name: mvp-scope
description: "Refine and validate MVP scope from PRD. Ensures MVP is truly minimal and viable. Can be run standalone or after PRD workflow."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/2-plan-workflows/mvp-scope"
instructions: "{installed_path}/instructions.md"

# Templates
mvp_scope_template: "{installed_path}/mvp-scope-template.md"

# Input files
input_file_patterns:
  prd:
    description: "Product Requirements Document (required)"
    whole: "{output_folder}/prd.md"
    sharded: "{output_folder}/prd/index.md"
    load_strategy: "FULL_LOAD"

  product_brief:
    description: "Product brief (optional)"
    whole: "{output_folder}/*brief*.md"
    sharded: "{output_folder}/*brief*/index.md"
    load_strategy: "FULL_LOAD"

# Output files
status_file: "{output_folder}/bmm-workflow-status.yaml"
default_output_file: "{output_folder}/mvp-scope.md"

standalone: true

